namespace JsonServerKit.AppServer.Data
{
    /// <summary>
    /// Response from the server to a SessionRequest by a client.
    /// Designed to signal the end of client/server communication before either party is closing the connection.
    /// Purpose:
    /// -Server side tracking of a "session" as a transaction.
    /// -Control flow between client/server.
    /// </summary>
    public class SessionInfo
    {
        /// <summary>
        /// See <see cref="SessionRequest.SessionName"/>.
        /// </summary>
        public string SessionName { get; set; }

        /// <summary>
        /// Session Id generated by the server.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Session lifetime valid until this datetime.
        /// </summary>
        public DateTime ValidUntil { get; set; }

        /// <summary>
        /// Flag to signal the communication end.
        /// </summary>
        public bool CloseNow { get; set; }
    }
}
